source "https://rubygems.org"

gem "github-pages", group: :jekyll_plugins

gem "tzinfo-data"

group :jekyll_plugins do
	gem 'jekyll-optional-front-matter'
	gem 'jekyll-relative-links'
	gem 'jekyll-titles-from-headings'	
	gem "jekyll-sitemap"
	gem "jekyll-feed"
	gem "jemoji"
	gem "jekyll-include-cache"
	gem "jekyll-github-metadata"
end
